projectVersion=7.0.2-SNAPSHOT
# Maven group for the root project and all published subprojects
projectGroup=org.grails.plugins
grailsVersion=7.0.0
# Comma-separated list of projects to publish
projectsToPublish=i18n-enums

# Build dependencies
asciidoctorVersion=4.0.5
checkstyleVersion=10.21.4
codenarcVersion=3.6.0
jacocoVersion=0.8.12
testLoggerVersion=4.0.0

# This prevents the Grails Gradle Plugin from unnecessarily excluding slf4j-simple in the generated POMs
# https://github.com/grails/grails-gradle-plugin/issues/222
slf4jPreventExclusion=true

# Enable and set agree=yes to publish build scans from GitHub workflows
ciBuildScanPublish=true
ciBuildScanTermsOfUseUrl=https://gradle.com/terms-of-service
ciBuildScanTermsOfUseAgree=yes

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
