---
project:
  name: "i18n-enums"
  title: "I18n Enums Plugin"
  description: "Adds an annotation usable on Enums to easily add and implement the\
    \ MessageSourceResolvable interface in a standard way throughout a Grails project."
  org: "Grails Plugins"
github:
  org: "grails-plugins"
  project: "i18n-enums"
license:
  name: "Apache-2.0"
contributors:
  sbglasius: "Søren Berg Glasius"
  jdaugherty: "James Daugherty"
  burtbeckwith: "Burt Beckwith"
  bkoehm: "Brian Koehmstedt"
  jamesfredley: "James Fredley"
  dauer: "Thomas Rasmussen"
versions:
  current: "7.0.1"
  previous:
  - "7.0.1"
  - "7.0.0"
  ignore:
  - "snapshot"
  - "7.0.x"
