plugins {
    id 'config.example-app'
}

version = projectVersion
group = 'app1'

dependencies {

    profile 'org.apache.grails.profiles:web'
    console 'org.apache.grails:grails-console'

    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation project(':i18n-enums')

    implementation 'org.apache.grails:grails-core'
    implementation 'org.apache.grails:grails-databinding'
    implementation 'org.apache.grails:grails-gsp'
    implementation 'org.apache.grails:grails-interceptors'
    implementation 'org.apache.grails:grails-layout'
    implementation 'org.apache.grails:grails-logging'
    implementation 'org.apache.grails:grails-services'
    implementation 'org.apache.grails:grails-url-mappings'
    implementation 'org.apache.grails:grails-web-boot'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-logging'
    implementation 'org.springframework.boot:spring-boot-starter-tomcat'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    runtimeOnly 'cloud.wondrify:asset-pipeline-grails'
    runtimeOnly 'org.fusesource.jansi:jansi'

    integrationTestImplementation testFixtures('org.apache.grails:grails-geb')

    testImplementation 'org.apache.grails:grails-testing-support-web'
    testImplementation 'org.spockframework:spock-core'
}
